### ISSUE TITLE
Deployment on AEM Cloud Manager fails 

### ISSUE THREAD

**Issue by NmurtasDev** [Netcentric/accesscontroltool#672] opened 2023-09-14 16:25 UTC
## Required Information

* [ ] Netcentric version: 3.0.9
* [ ] Reproducible on Latest? yes

### Expected Behavior

The deployment should done correctly

### Actual Behavior

The AEM Cloud Manager pipeline is failing due to a severity critical error related to the following message:

**The product interface org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.dumpservice.impl.DumpServiceImpl$1 contained in /apps/netcentric/actool/install/accesscontroltool-bundle-3.0.9.jar.**

**The product interface org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType should not be implemented by custom code. Detected in biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthInstallerUserManagerPrefetchingImpl$1 contained in /apps/netcentric/actool/install/accesscontroltool-bundle-3.0.9.jar.**

### Steps to Reproduce

Include netcentric dependencies in the following files:

pom.xml
 <dependency>
                <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                <artifactId>accesscontroltool-package</artifactId>
                <type>content-package</type>
                <version>3.0.9</version>
                <classifier>cloud</classifier>
            </dependency>
            
            <dependency>
                <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                <artifactId>accesscontroltool-oakindex-package</artifactId>
                <type>zip</type>
                <version>3.0.9</version>
                <classifier>cloud</classifier>
            </dependency>

all/pom.xml
 <embeddeds>
    <embedded>
                            <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                            <artifactId>accesscontroltool-oakindex-package</artifactId>
                            <type>zip</type>
                            <target>/apps/vwgroupitaemaacs-packages/application/install</target>
                        </embedded>
                    </embeddeds>
                    <subPackages>
                        <subPackage>
                            <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                            <artifactId>accesscontroltool-package</artifactId>
                            <classifier>cloud</classifier>
                            <filter>true</filter>
                        </subPackage>
                    </subPackages>

**Comment by kwin** [comment] 2023-09-14 16:43
Duplicate of #671

**Closed as not planned by kwin** 2023-09-14 16:43 UTC

**Comment by NmurtasDev** [comment] 2023-09-14 16:44
Sorry @kwin,
my bad i don see the other bug 
thx for closing and linking
