### ISSUE TITLE
Permissions get removed from groups configured in ACL Tool

### ISSUE THREAD

**Issue by mittalkunal** [Netcentric/accesscontroltool#216] opened 2017-08-09 11:16 UTC
I know that when ACL tool runs on AEM it first removes all the permissions related to users / groups configured in ACL tool. 

We have a use case where we have set of permissions for a group that get configured within ACL Tool and then some of the permission are added via application code based on workflows / observation listeners. I can think of a solution like :

- authors_group_custom:

  - name: AEM Authors custom group
    description: abc custom
    rewritePermissions: false
    path: custom

- authors_group:

   - name: AEM Authors group
      isMemberOf: authors_group_custom
      description: abc
      path: custom

In this case adding "rewritePermissions" property will disable the ACL tool to remove the permissions associated to that group and because the second group has membership to custom group, all the permissions would be inherited. 

So via ACL tool we configure ACLs only for authors_group group and not custom group. For custom group permissions can come from AEM Application code.

**Comment by ghenzler** [comment] 2017-08-14 13:29
So we do have https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-memberships-to-dynamic-groups already (for the case your custom code would create the group `authors_group_custom` you could use that to reference it in `authors_group` without deleting the relationship during the next run of the AC Tool (be sure you use a version >=2.0.0)

if you want to create the group `authors_group_custom` with the AC Tool, but you would like to control the permissions in the content for that group, I think this issue is a duplicate of
#212 (not yet implemented though)
Do you think the `restrictAcesToPaths` property would work for you?

**Comment by mittalkunal** [comment] 2017-08-15 12:00
Thanks for your reply on this @ghenzler.

The first option does not work for me because unfortunately I need a feature to be able to add more ACLs for a group which don't get removed when acl tool runs next time.

In this use case we are adding permissions to Assets directly so restricting based on paths will be very difficult unfortunately.

**Comment by ghenzler** [comment] 2018-04-20 06:39
In the meantime #212  and https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#limiting-where-the-ac-tool-creates-and-removes-aces is available. This should help for your use case.

**Closed by ghenzler** 2018-04-20 06:39 UTC
