### ISSUE TITLE
/oak:index/repACL-custom-1 triggers an AEMaaCS Code Validation error - Standard format not followed 

### ISSUE THREAD

**Issue by diogopedreira** [Netcentric/accesscontroltool#681] opened 2023-12-20 11:57 UTC
I've noticed that, at least from Cloud Manager's December release, the Code Scanning that runs as part of any pipeline, started complaining with the fact that the /oak:index/repACL-custom-1 is not following the standards (finding entry below)

> 2023-12-20T11:07:52.15Z,**Netcentric:accesscontroltool-oakindex-package:3.0.10**,0,"**Index definition detected at /oak:index/repACL-custom-1**. **Fully custom index names need to follow the pattern <prefix>.<name>-custom-<version>**, e.g. /oak:index/acme.indexName-custom-1, to be compliant with AEM as a Cloud Service",Code Smell,Minor,,IndexValidFullyCustomName,"aem,cloud-service-compatibility",**https://www.adobe.com/go/aem_cmcq_indexvalidfullycusto_en**

Reworking the index name, in a similar action like the one made in https://github.com/Netcentric/accesscontroltool/pull/550 (targeting just the index itself) and https://github.com/Netcentric/accesscontroltool/pull/638, would fix the issue.

@kwin please let me know if this would be enough and I would gladly help with the change if you want me to.

**Comment by kwin** [comment] 2023-12-20 12:11
Seems like the guidelines have changed again. Now https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/operations/indexing#index-names states:

> Fully custom index: It is possible to create an entirely new index from scratch. Their name must have a prefix to avoid naming conflicts. For instance: /oak:index/acme.product-1-custom-2, where the prefix is acme.

**Comment by kwin** [comment] 2023-12-20 12:13
@diogopedreira Can you come up with a PR for refactoring the name again?

**Comment by diogopedreira** [comment] 2023-12-20 15:12
@kwin, done https://github.com/Netcentric/accesscontroltool/pull/682. I've made a comment assuming a version number that I'm not 100% sure, as such let me know if it's ok or not so I can adjust and please poke me there if you want me to address any other topic.

**Comment by kwin** [comment] 2024-05-06 09:19
I cannot reproduce the issue with 3.0.10 on Cloud Manager with AEM.
I embedded `accesscontroltool-oakindex-package` and it is installed fine, and I see no related issue in the code check report. I assume this was a false positive from Adobe and meanwhile fixed in Cloud Manager. Please reopen if you still see an issue @diogopedreira

**Closed as not planned by kwin** 2024-05-06 09:19 UTC
