### ISSUE TITLE
Problem with index

### ISSUE THREAD

**Issue by Shaihuludus** [Netcentric/accesscontroltool#586] opened 2021-06-17 11:19 UTC
- I have installed accesscontroltool vs 2.8.0
- I'm using install hook to install acl-s
- I have index created:

```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:oak="http://jackrabbit.apache.org/oak/ns/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"    xmlns:nt="http://www.jcp.org/jcr/nt/1.0" xmlns:rep="internal"     
    jcr:primaryType="oak:QueryIndexDefinition" 
    async="async"
    compatVersion="{Long}2" 
    type="lucene"> 
<indexRules jcr:primaryType="nt:unstructured"> 
        <rep:ACL jcr:primaryType="nt:unstructured"> 
            <properties jcr:primaryType="nt:unstructured"> 
                <primaryType 
                    jcr:primaryType="nt:unstructured" 
                    name="jcr:primaryType" 
                    propertyIndex="{Boolean}true"/> 
                <mixinTypes 
                    jcr:primaryType="nt:unstructured" 
                    name="jcr:mixinTypes" 
                    propertyIndex="{Boolean}true"/> 
            </properties> 
        </rep:ACL> 
    </indexRules> 
</jcr:root>
```

Unfortunately I still get 
```
Exception while installing configurations: java.lang.IllegalStateException: Could not query repository for existing ACLs: org.apache.jackrabbit.oak.query.RuntimeNodeTraversalException: The query read or traversed more than 100000 nodes. To avoid affecting other tasks, processing was stopped. 
Error during processing:

org.apache.jackrabbit.vault.packaging.PackageException: Error while executing an install hook during prepare phase.
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:230)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:401)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:354)
	at com.day.crx.packaging.impl.J2EEPackageManager.consoleInstall(J2EEPackageManager.java:354)
	at com.day.crx.packaging.impl.J2EEPackageManager.doPost(J2EEPackageManager.java:204)
	at com.day.crx.packaging.impl.PackageManagerServlet.doPost(PackageManagerServlet.java:172)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
(...)
```

Is there any solution for this? Maybe different way of installing acl?

**Comment by kwin** [comment] 2024-06-04 21:27
Probably a duplicate of #714

**Closed as not planned** 2024-06-04 21:28 UTC
