### ISSUE TITLE
AC Tool should check on startup if the current YAML file is already processed or not

### ISSUE THREAD

**Issue by henrykuijpers** [Netcentric/accesscontroltool#241] opened 2017-11-22 14:23 UTC
Issue:
Deploying the AC Tool + YAML config the first time

The AC Tool gets installed, YAML config also added -> AC Tool doesn't "see" the YAML change -> Doesn't process the YAML file

Set up:
project-config (contains OSGi runmode configs (also the configs for AC Tool) + YAML file)
project-all-nodeps (contains project-view, project-config, etc)
project-all (contains project-all-nodeps + all other dependencies including AC Tool bundle)

Probably the tool should check on startup if there are any YAML files in the configured path, that still need to be processed
(Using Upload Listener Service) https://github.com/Netcentric/accesscontroltool/blob/ff52c1bc65186a9823695a3a6cba21be428eea94/docs/ApplyConfig.md#upload-listener-service

**Comment by kwin** [comment] 2017-11-22 15:48
This is related to #210. In the best case the package manager would be able to figure out the dependency and would only install the project-config package once the project-all (especially the ACTool and the bundle within) has been successfully installed. When leveraging the install-hook mechanism there is nothing we can do here, but indeed for the upload listener there would be the possibility to check for existing resources once started.
@henrykuijpers Would you be able to extend the PR at #239 to make sure that initially once the listener is started it processes already existing yaml files?

**Comment by ghenzler** [comment] 2017-12-01 07:34
Let's close this as duplicate of #210

**Closed by ghenzler** 2017-12-01 07:34 UTC
