### ISSUE TITLE
Upload listener creates stackoverflow exception because wrong method is called

### ISSUE THREAD

**Issue by royteeuwen** [Netcentric/accesscontroltool#222] opened 2017-09-13 16:23 UTC
Hey guys,

It seems that your upload listener creates a stackoverflow because it calls aceService.execute(), which call's itself indefinitly (I guess the execute() should actually call the apply() internally for the AcInstallationServiceImpl)

Greets,
Roy

https://github.com/Netcentric/accesscontroltool/blob/7f671e6596e0a73678f02145d41a06373fcd0687/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configuploadlistener/impl/UploadListenerServiceImpl.java#L101

https://github.com/Netcentric/accesscontroltool/blob/7f671e6596e0a73678f02145d41a06373fcd0687/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java#L741

**Comment by kwin** [comment] 2017-09-15 16:19
Seem that this is a regression caused by the fix for #157 (this is the commit: https://github.com/Netcentric/accesscontroltool/commit/02fa267814ba59ca0a3276fccf6cac826e063fc7). Actually almost all execute methods in https://github.com/Netcentric/accesscontroltool/blob/7f671e6596e0a73678f02145d41a06373fcd0687/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java#L741 are affected. @ghenzler Could you look into that?

**Comment by patkinson01** [comment] 2017-10-09 15:30
Hi guys, don't suppose you have any idea on ETA yet for this fix do you please? Wondering whether to wait or rollback (to v1.9.6?). Thanks!

**Comment by ghenzler** [comment] 2017-10-09 22:25
I will look into this in two weeks when I'm back from vacation - @patkinson01 the best workaround is to use the install hook instead.

**Comment by patkinson01** [comment] 2017-10-10 06:44
Hi @ghenzler, the issue for us is that the install hook now isn't working so we're having to manually apply via JMX console after each package deploy.  Thanks for the update, have a great vacation! :)

**Comment by ghenzler** [comment] 2017-10-18 10:28
Fixed with https://github.com/Netcentric/accesscontroltool/pull/224

**Closed** 2017-10-18 10:29 UTC
Labels: bug

**Comment by royteeuwen** [comment] 2017-10-18 10:53
@ghenzler  Thanks :)! will there be a release of this?

**Comment by ghenzler** [comment] 2017-10-18 16:05
@royteeuwen I just released [v2.0.2](https://github.com/Netcentric/accesscontroltool/releases/tag/2.0.2), in a few hours it will become available via maven central.

**Comment by patkinson01** [comment] 2017-10-24 17:31
Great job, thank you so much @ghenzler! :)

**Comment by royteeuwen** [comment] 2017-10-24 18:53
yup thanks @ghenzler ! works like a charm
