### ISSUE TITLE
AC Tool should be cluster-aware

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#217] opened 2017-08-23 07:13 UTC
(AEM 6.1, AC Tool 1.9.5)

When the AC tool is deployed on a cluster, the situation can occur that the AC Tool is started on more than 1 cluster node in parallel, thus leading to merge exceptions when persisting data to the repository (both ACLs and the history).

The AC Tool should run only a single cluster node; or when running on multiple cluster nodes, it should not run in parallel, thus avoiding exceptions like this; for me it is not clear what the impact of this exception is (we will probably run the tool again just to make sure).

```
23.08.2017 08:34:53.424 *ERROR* [OsgiInstallerImpl-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl RepositoryException:
javax.jcr.InvalidItemStateException: OakState0001: Unresolved conflicts in /var/statistics/achistory
                at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:237)
                at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:212)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:661)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:487)
                at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:424)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:266)
                at org.apache.jackrabbit.oak.jcr.session.SessionImpl.save(SessionImpl.java:421)
                at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:497)
                at org.apache.sling.jcr.base.SessionProxyHandler$SessionProxyInvocationHandler.invoke(SessionProxyHandler.java:113)
                at com.sun.proxy.$Proxy12.save(Unknown Source)
                at biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistHistory(AcHistoryServiceImpl.java:91)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installConfigurationFiles(AceServiceImpl.java:209)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:134)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:118)
                at com.foobar.startup.StartupCheckServlet.activate(StartupCheckServlet.java:48)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
…
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakState0001: Unresolved conflicts in /var/statistics/achistory
                at org.apache.jackrabbit.oak.plugins.commit.ConflictValidator.failOnMergeConflict(ConflictValidator.java:115)
                at org.apache.jackrabbit.oak.plugins.commit.ConflictValidator.propertyAdded(ConflictValidator.java:84)
                at org.apache.jackrabbit.oak.spi.commit.CompositeEditor.propertyAdded(CompositeEditor.java:83)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.propertyAdded(EditorDiff.java:82)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:378)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.process(EditorDiff.java:52)
                at org.apache.jackrabbit.oak.spi.commit.EditorHook.processCommit(EditorHook.java:54)
                at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
                at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch$InMemory.merge(DocumentNodeStoreBranch.java:543)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch.merge0(DocumentNodeStoreBranch.java:223)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch.merge(DocumentNodeStoreBranch.java:171)
                at org.apache.jackrabbit.oak.plugins.document.DocumentRootBuilder.merge(DocumentRootBuilder.java:158)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore.merge(DocumentNodeStore.java:1497)
                at org.apache.jackrabbit.oak.core.MutableRoot.commit(MutableRoot.java:247)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.commit(SessionDelegate.java:339)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:485)
                ... 92 common frames omitted
 ```

**Comment by kwin** [comment] 2017-08-24 09:53
Hi @joerghoh, I recommend using a content package with the supplied install hook to install ACLs. That way you have direct synchronous feedback in case installation fails and also some error message being exposed when installing it via the package manager ReSTful API. Still this is of course a valid issue and should be fixed.

**Comment by ghenzler** [comment] 2017-08-31 20:25
@joerghoh Which way of triggering the AC Installation did produce the above exception? (https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md) 

> we will probably run the tool again just to make sure

Did it then run successfully?

**Comment by joerghoh** [comment] 2017-09-01 06:48
it did.

I will check if we can trigger the run by the install hook.

**Comment by kwin** [comment] 2017-11-07 12:25
To solve that we need to check for property {{event.application}} in our OSGi Event Listener (compare with http://sling.apache.org/documentation/the-sling-engine/resources.html#resource-observation)

**Comment by ghenzler** [comment] 2017-11-17 08:54
@joerghoh Just to make sure, you used https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#upload-listener-service when you ran into the problem? (all other means should be cluster-aware)

**Comment by kwin** [comment] 2017-11-21 09:25
The stacktrace above looks weird
{code}
at biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistHistory(AcHistoryServiceImpl.java:91)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installConfigurationFiles(AceServiceImpl.java:209)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:134)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:118)
                at com.foobar.startup.StartupCheckServlet.activate(StartupCheckServlet.java:48)
{code}

There seems to be a custom StartupCheckServlet which triggered the AceService programmatically.

**Comment by joerghoh** [comment] 2017-11-21 09:37
@kwin that's correct. We already removed this "startup" servlet, which was weird hack anyway.

**Comment by kwin** [comment] 2017-11-21 09:43
In case of using triggering ACTool programmatically it is the responsibility of the called to be cluster aware. @joerghoh can you reproduce the same issue with the built-in listener? Because that in theory could run into the same issue.

**Closed** 2017-11-22 19:35 UTC
Labels: bug
