### ISSUE TITLE
keepOrder not working when used for all entries of a path

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#129] opened 2016-10-28 08:01 UTC
The attached file does not work. All allows are on top, all denys on bottom.

[keep.txt](https://github.com/Netcentric/accesscontroltool/files/557848/keep.txt)

**Comment by ghenzler** [comment] 2017-02-06 20:39
The root cause is the fact that you use multiple group declaration when you only need one, the following snippet fixes it:

```
    - keep-order1:

       - path: /content
         permission: allow
         actions: read

       - path: /apps/keeporder
         permission: allow
         actions: read
         keepOrder: true

    - keep-order2:

       - path: /apps/keeporder
         permission: deny
         actions: read
         keepOrder: true

    - keep-order3:

       - path: /content
         permission: allow
         actions: read

       - path: /apps/keeporder
         permission: allow
         actions: read
         keepOrder: true

    - keep-order4:

       - path: /apps/keeporder
         permission: deny
         actions: read
         keepOrder: true
```
If you put `/content` in a separate declaration for `keep-order1` and `keep-order1`, those Sets are created already and the sets for 2 and 4 not yet. 

There is no easy fix (except avoiding duplicate declarations, this was at one time even forbidden #73), leaving this open for now.

**Comment by ghenzler** [comment] 2017-04-11 09:10
To be fixed by changing the config model to not use the nested map (but a plain path-sorted list of AceBeans).

**Closed** 2017-04-21 15:23 UTC
Labels: bug
