### ISSUE TITLE
Interface JackrabbitAccessControlEntry annotated with @ProviderType

### ISSUE THREAD

**Issue by kum-sushil** [Netcentric/accesscontroltool#589] opened 2021-08-03 05:04 UTC
We are facing issues with the service build for non AEMaaCS. We are  using Netcentric acltool version **2.8.0**, 
maven dependency:--
<dependency>
                <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                <artifactId>accesscontroltool-package</artifactId>
                <type>content-package</type>
                <version>${actool.version}</version>
            </dependency>
            <dependency>
                <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
                <artifactId>accesscontroltool-oakindex-package</artifactId>
                <type>zip</type>
                <version>${actool.version}</version>
            </dependency>

On sonar build we are getting below issues, **#1 being critical one**

1.  The product interface org.apache.jackrabbit.api.security.JackrabbitAccessControlEntry 
annotated with @ProviderType should not be implemented by custom code. 
Detected in biz.netcentric.cq.tools.actool.helper.AceWrapper contained in 
/apps/netcentric/actool/install/accesscontroltool-bundle-2.8.0.jar.

2. Inclusion of both /etc/packages/Netcentric/accesscontroltool-package-2.8.0.zip/jcr:content and /apps/mcet-packages in the same package violates the separation of immutable and mutable paths in the same package.

3. Inclusion of both /etc/packages/Netcentric/accesscontroltool-content-package-2.8.0.zip/jcr:content and /apps/netcentric in the same package violates the separation of immutable and mutable paths in the same package.

**Comment by ghenzler** [comment] 2021-08-04 07:56
I think this is a duplicate of #584 that was fixed in version 3.0.1?

**Closed as completed by ghenzler** 2021-08-04 07:56 UTC
Labels: duplicate
